- name: TASKS | HOST_PACKAGES | Install libguestfs-tools, jq
  apt:
    name:
      - libguestfs-tools
      - jq
      - python3-pip
      - grep
      - gzip
    state: present
    update_cache: yes
  register: install_packages
  until: install_packages is succeeded
  retries: 3
  delay: 10

- name: TASKS | HOST_PACKAGES | Install Proxmoxer
  ansible.builtin.pip:
    name:
      - proxmoxer
      - requests
    break_system_packages: true
  register: install_proxmoxer
  until: install_proxmoxer is succeeded
  retries: 3
  delay: 10
