---
- name: TASKS | VM_FIREWALL | Set Firewall Options
  ansible.builtin.shell: |
    pvesh set /nodes/{{ local_pve_node.stdout }}/qemu/{{ pve_vm_id }}/firewall/options{% for key, value in pve_vm_firewall_options.items() %} --{{ key }} '{{ value }}'{% endfor %}
  args:
    executable: /bin/bash
  when:
    - pve_vm_firewall_options is defined

- name: TASKS | VM_FIREWALL | Create Firewall IPSets
  ansible.builtin.shell: |
    if ! pvesh get /nodes/{{ local_pve_node.stdout }}/qemu/{{ pve_vm_id }}/firewall/ipset/{{ item.name }} >/dev/null 2>&1; then
      pvesh create /nodes/{{ local_pve_node.stdout }}/qemu/{{ pve_vm_id }}/firewall/ipset{% for key, value in item.items() %} --{{ key }} '{{ value }}'{% endfor %}
    else
      echo "IPSet {{ item.name }} already exists for VM {{ pve_vm_id }}"
    fi
  args:
    executable: /bin/bash
  with_items: "{{ pve_vm_firewall_ipsets }}"
  when:
    - pve_vm_firewall_ipsets is defined
  register: firewall_ipsets_result
  retries: 3
  delay: 5
  until: firewall_ipsets_result is succeeded
  ignore_errors: yes